version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./postgresql_setup/init.sql:/docker-entrypoint-initdb.d/init.sql

    sensors_api:
        image: cristiro/air-pollution-sensors-api
        ports:
        - "8080:5000"
        depends_on:
        - db
